apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-task-deploy
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: biocad-test-task
        image: vyrupaevmatvei/biocad_test_task:latest
        ports:
        - containerPort: 32777